Cache dependency docker images

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -33,9 +33,9 @@ jobs:
     strategy:
       matrix:
         database-combo:
-          - { postgres: "15", mysql: "8.0" }
-          - { postgres: "16", mysql: "8.4" }
-          - { postgres: "17", mysql: "9.1" }
+          - { postgres: "15", mysql: "8.0", minio: "RELEASE.2024-11-07T00-52-20Z", gcs: "1.50.2", azurite: "3.33.0", azure-storage-blob: "12.26.0" }
+          - { postgres: "16", mysql: "8.4", minio: "RELEASE.2024-11-07T00-52-20Z", gcs: "1.50.2", azurite: "3.33.0", azure-storage-blob: "12.26.0" }
+          - { postgres: "17", mysql: "9.1", minio: "RELEASE.2024-11-07T00-52-20Z", gcs: "1.50.2", azurite: "3.33.0", azure-storage-blob: "12.26.0" }
 
     name: Test PostgreSQL ${{ matrix.database-combo.postgres }} & MySQL ${{ matrix.database-combo.mysql }}
 
@@ -83,16 +83,73 @@ jobs:
         run: poetry install --no-interaction
 
       #----------------------------------------------
+      # Cache or Restore docker images
+      #----------------------------------------------
+      - name: Cache Docker images
+        id: cache-docker-images
+        uses: actions/cache@v4
+        with:
+          path: /tmp/.docker  # This path stores the Docker images and cache
+          key: ${{ runner.os }}-docker-images-${{ matrix.database-combo.postgres }}-${{ matrix.database-combo.mysql }}
+          restore-keys: |
+            ${{ runner.os }}-docker-images-
+
+      #----------------------------------------------
+      # Pull does not exist docker images
+      #----------------------------------------------
+      - name: Pull Dependency Docker images
+        run: |
+          # Pull PostgreSQL image if not cached
+          if ! docker image inspect postgres:${{ matrix.database-combo.postgres }} > /dev/null 2>&1; then
+            echo "PostgreSQL image not found locally. Pulling image..."
+            docker pull postgres:${{ matrix.database-combo.postgres }}
+          else
+            echo "PostgreSQL image already exists. Using cache."
+          fi
+
+          # Pull MySQL image if not cached
+          if ! docker image inspect mysql:${{ matrix.database-combo.mysql }} > /dev/null 2>&1; then
+            echo "MySQL image not found locally. Pulling image..."
+            docker pull mysql:${{ matrix.database-combo.mysql }}
+          else
+            echo "MySQL image already exists. Using cache."
+          fi
+
+          # Pull Minio image if not cached
+          if ! docker image inspect minio/minio:${{ matrix.database-combo.minio }} > /dev/null 2>&1; then
+            echo "Minio image not found locally. Pulling image..."
+            docker pull minio/minio:${{ matrix.database-combo.minio }}
+          else
+            echo "Minio image already exists. Using cache."
+          fi
+
+          # Pull Fake GCS Server image if not cached
+          if ! docker image inspect fsouza/fake-gcs-server:${{ matrix.database-combo.gcs }} > /dev/null 2>&1; then
+            echo "Fake GCS Server image not found locally. Pulling image..."
+            docker pull fsouza/fake-gcs-server:${{ matrix.database-combo.gcs }}
+          else
+            echo "Fake GCS Server image already exists. Using cache."
+          fi
+
+          # Pull Azurite image if not cached
+          if ! docker image inspect mcr.microsoft.com/azure-storage/azurite:${{ matrix.database-combo.azurite }} > /dev/null 2>&1; then
+            echo "Azurite image not found locally. Pulling image..."
+            docker pull mcr.microsoft.com/azure-storage/azurite:${{ matrix.database-combo.azurite }}
+          else
+            echo "Azurite image already exists. Using cache."
+          fi
+
+      #----------------------------------------------
       # Overwrite .env file to test different version of databases
       #----------------------------------------------
       - name: Set up .env file
         run: |
           echo "POSTGRES_VERSION=${{ matrix.database-combo.postgres }}" > .env
           echo "MYSQL_VERSION=${{ matrix.database-combo.mysql }}" >> .env
-          echo "MINIO_VERSION=RELEASE.2024-11-07T00-52-20Z" >> .env
-          echo "FAKE_GCS_SERVER_VERSION=1.50.2" >> .env
-          echo "AZURITE_VERSION=3.33.0" >> .env
-          echo "AZURE_STORAGE_BLOB_VERSION=12.26.0" >> .env
+          echo "MINIO_VERSION=${{ matrix.database-combo.minio }}" >> .env
+          echo "FAKE_GCS_SERVER_VERSION=${{ matrix.database-combo.gcs }}" >> .env
+          echo "AZURITE_VERSION=${{ matrix.database-combo.azurite }}" >> .env
+          echo "AZURE_STORAGE_BLOB_VERSION=${{ matrix.database-combo.azure-storage-blob }}" >> .env
 
       #----------------------------------------------
       #              run test suite
